HTTP/1.1 201 Created
Vary: Origin
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 226
Date: Sun, 25 Jan 2026 23:09:52 GMT
Connection: close

{
  "id": "f1e8b83b-fdf3-4964-8659-31d55136eda4",
  "name": "The Great Gatsby",
  "author": "F. Scott Fitzgerald",
  "description": "A novel about the American Dream set in the Jazz Age",
  "price": 12.99,
  "image": "https://example.com/gatsby.jpg"
}