HTTP/1.1 501 Not Implemented
Vary: Origin
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 43
Date: Sun, 25 Jan 2026 03:44:02 GMT
Connection: close

{
  "error": "Create book not yet implemented"
}